# -*- coding: utf-8 -*-
"""
/***************************************************************************
 LPIS
                                 A QGIS plugin
 Plugin for LPIS ETS QA
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2019-03-04
        git sha              : $Format:%H$
        copyright            : (C) 2019 by Jethro
        email                : xtompok@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from PyQt5.QtCore import QSettings, QTranslator, qVersion, QCoreApplication, Qt
from PyQt5.QtGui import QIcon
from PyQt5.QtWidgets import QAction, QApplication
# Initialize Qt resources from file resources.py
from .resources import *
from qgis.core import QgsProject

# Import the code for the DockWidget
from .lpis_dockwidget import LPISDockWidget
import os.path

LPIS_ID_ATTRIBUTE = "NKOD_PB"
ETS_ID_ATTRIBUTE = "NKOD"


class LPIS:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface

        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)

        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'LPIS_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)

            if qVersion() > '4.3.3':
                QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&LPIS ETS plugin')
        # TODO: We are going to let the user set this up in a future iteration
        self.toolbar = self.iface.addToolBar(u'LPIS')
        self.toolbar.setObjectName(u'LPIS')

        #print "** INITIALIZING LPIS"

        self.pluginIsActive = False
        self.dockwidget = None

        self.lpisLayer = None
        self.workLayer = None


    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('LPIS', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            self.toolbar.addAction(action)

        if add_to_menu:
            self.iface.addPluginToVectorMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action


    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/lpis/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'LPIS'),
            callback=self.run,
            parent=self.iface.mainWindow())

    #--------------------------------------------------------------------------

    def onClosePlugin(self):
        """Cleanup necessary items here when plugin dockwidget is closed"""

        #print "** CLOSING LPIS"

        # disconnects
        self.dockwidget.closingPlugin.disconnect(self.onClosePlugin)

        # remove this statement if dockwidget is to remain
        # for reuse if plugin is reopened
        # Commented next statement since it causes QGIS crashe
        # when closing the docked window:
        # self.dockwidget = None

        self.pluginIsActive = False


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""

        #print "** UNLOAD LPIS"

        for action in self.actions:
            self.iface.removePluginVectorMenu(
                self.tr(u'&LPIS ETS plugin'),
                action)
            self.iface.removeToolBarIcon(action)
        # remove the toolbar
        del self.toolbar

    #--------------------------------------------------------------------------
    def updateNumbers(self,flpis,fets):
        self.dockwidget.areaLabel.setText(str(fets.geometry().area()))
        self.dockwidget.v1Label.setText(str(self.calculateV1(flpis,fets)))
        self.dockwidget.v2Label.setText(str(self.calculateV2(flpis,fets)))
        self.dockwidget.condLabel.setText(str(self.calculateCond(flpis,fets)))

    def calculateV1(self,flpis,fets):
        return 100.0*fets.geometry().area()/flpis.geometry().area()

    def calculateV2(self,flpis,fets):
        return fets.geometry().area() - flpis.geometry().area()
    
    def calculateCond(self,flpis,fets):
        arlpis = flpis.geometry().area()
        arets = fets.geometry().area()  
        v1 = self.calculateV1(flpis,fets)
        v2 = self.calculateV2(flpis,fets)
        if arlpis > 5000:
           if (v1 > 97 and v1 < 103) and (v2 > -10000 and v2 < 10000):
               return True   
        elif arlpis > 2000:
           if v1 > 95 and v1 < 105:
               return True
        else:
           if v1 > 93 and v1 < 107:
               return True
        return False


    def geometryUpdated(self,fid,geometry):
        self.dockwidget.v2Label.setText(str(geometry.area()))
        self.updateNumbers(self.curLpisFeature,self.workLayer.getFeature(fid))
    
    def featureAdded(self,fid):
        feat = self.workLayer.getFeature(fid)
        feat[ETS_ID_ATTRIBUTE] = self.curLpisFeature[LPIS_ID_ATTRIBUTE]
        self.workLayer.updateFeature(feat)
        self.updateNumbers(self.curLpisFeature,feat)
        self.statl.setText("Feature {} added".format(fid))


    def workLayerChanged(self,name):
        self.workLayer = QgsProject.instance().mapLayersByName(name)[0]        
        self.workLayer.geometryChanged.connect(self.geometryUpdated)
        self.workLayer.featureAdded.connect(self.featureAdded)

    def lpisLayerChanged(self,name):
        self.lpisLayer = QgsProject.instance().mapLayersByName(name)[0]        
        
    def vectorizePolygon(self):
        selected = list(self.lpisLayer.getSelectedFeatures())
        if len(selected) == 0:
                self.statl.setText("Neni vybrany objekt v LPIS vrstve")
                return
        if len(selected) > 1:
                self.statl.setText("Je vybrano vice objektu v LPIS vrstve")
                return
        poly = selected[0]
        self.statl.setText("Vybran polygon {}".format(poly.attribute(LPIS_ID_ATTRIBUTE)))

        cb = QApplication.clipboard()
        cb.clear(mode = cb.Clipboard)
        cb.setText(str(poly.attribute(LPIS_ID_ATTRIBUTE)))
        
        self.curLpisFeature = poly
        self.iface.setActiveLayer(self.workLayer)
        self.workLayer.startEditing()
        self.iface.actionAddFeature().trigger()

            


    def run(self):
        """Run method that loads and starts the plugin"""

        if not self.pluginIsActive:
            self.pluginIsActive = True

            #print "** STARTING LPIS"

            # dockwidget may not exist if:
            #    first run of plugin
            #    removed on close (see self.onClosePlugin method)
            if self.dockwidget == None:
                # Create the dockwidget (after translation) and keep reference
                self.dockwidget = LPISDockWidget()

            # connect to provide cleanup on closing of dockwidget
            self.dockwidget.closingPlugin.connect(self.onClosePlugin)

            # show the dockwidget
            # TODO: fix to allow choice of dock location
            self.iface.addDockWidget(Qt.RightDockWidgetArea, self.dockwidget)
            self.dockwidget.show()

            self.statl = self.dockwidget.statusLabel

            lpisCombo = self.dockwidget.lpisLayerComboBox
            etsCombo = self.dockwidget.workLayerComboBox
            lpisCombo.currentIndexChanged[str].connect(self.lpisLayerChanged)
            etsCombo.currentIndexChanged[str].connect(self.workLayerChanged)
            self.dockwidget.vectorizeButton.clicked.connect(self.vectorizePolygon)

            layers = QgsProject.instance().mapLayers()
            for layer in layers.values():
                lpisCombo.addItem(layer.name())
                etsCombo.addItem(layer.name())
            
            self.statl.setText(etsCombo.currentText())
            self.workLayer = QgsProject.instance().mapLayersByName(etsCombo.currentText())[0] 
            self.lpisLayer = QgsProject.instance().mapLayersByName(lpisCombo.currentText())[0]        


